version: 2
jobs:
  build:
    docker:
      - image: circleci/node:9.4.0
    steps:
      # Install python dev and pip
      - run: sudo apt install python-pip python-dev 
      - run: sudo pip install awscli

      - checkout
      - run: echo "This section is intentionally skipped."
      - deploy:
          name: Deploy Branches
          command: |
            aws --region eu-west-1 s3 ls